### PR TITLE
Added Vagrantfile specific to ficus

### PR DESCRIPTION
**Pull request by johnbaldwin**
Configuration Pull Request
---

Make sure that the following steps are done before merging

  - [x] @devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overridden when this goes live?  
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

### CODE REVIEW

**Comment by johnbaldwin** [comment]
@briandant Please let me know if this works for you. You should be able to set up a devstack without setting the `OPENEDX_RELEASE` ENV var. I'm curious if this works for you

**Comment by briandant** [comment]
@johnbaldwin: That part worked (the env var), but the git clean task failed. Is this common for you?

**Comment by bryanlandia** [comment]
@briandant Do you know what the error was?  Did it fail due to local modifications in edx-platform? 
cc @johnbaldwin

**Comment by briandant** [comment]
@bryanlandia: I just had changes in my local copy, which were (I guess) mirrored to the Vagrant box at that point. We could potentially put something like `git clean -xf` or whatever the Ansible playbook does, telling the user to run that on the host before running `vagrant up`. In hindsight, it's somewhat intuitive to deduce this as the solution, but if I missed it, maybe others will too?

**Comment by briandant** [comment]
And now my Ficus env is blown away and I'm on a slow network. Do you want me to retest @bryanlandia?

**Comment by bryanlandia** [comment]
@briandant is off on vacation.  @johnbaldwin What do you think about adding something like what Brian suggests (`git clean -xf`) on edx-platform before running?  I think it probably adds some complexity and new work you weren't intending with this PR.  From what I've seen it looks good, though I haven't tested it myself.

**Pull request merged**
