### PR TITLE
Hawthorn playbooks and Vagrantfiles cleanup

### PR DESCRIPTION
**Pull request by OmarIthawi**
### TODO
 - [x] Check that the Hawthorn playbooks has the latest roles enabled from upstream
 - [x] Remove old and unused roles in the upstream from the Hawthron playbooks

### CODE REVIEW

**Comment by OmarIthawi** [comment]
[(8) Clean-up and merge the config repo: Hawthorn](https://trello.com/c/dGF8RWPG/3309-8-clean-up-and-merge-the-config-repo-hawthorn)

**Comment by johnbaldwin** [comment]
@OmarIthawi Sorry for the delay in reviewing. This looks like it is a simple rename and cleanup, getting rid of Vagrantfiles since Hawthorn devstack is now docker based. Am I missing anything?

**Review by johnbaldwin — APPROVED** [review]

**Comment by OmarIthawi** [comment]
Indeed @johnbaldwin! That's about it.

I need to go through the TODO's though.

Thanks for the review :)

**Review by thraxil — APPROVED** [review]

**Comment by OmarIthawi** [comment]
@thraxil @johnbaldwin thanks!

**Pull request merged**
