### PR TITLE
Tahoe: Get Ficus updates into Hawthorn

### PR DESCRIPTION
**Pull request by OmarIthawi**
Merging Ficus changes into Hawthorn as of March 18th, 2019.

### CODE REVIEW

**Comment by OmarIthawi** [comment]
@thraxil looks like we have a ton of conflicts, I can start fixing them one by one, but I'd like to hear what do you think?

**Comment by OmarIthawi** [comment]
[(2) Hawthorn: Sync with Ficus branches](https://trello.com/c/PJHIhP3E/3668-2-hawthorn-sync-with-ficus-branches)

**Comment by thraxil** [comment]
@OmarIthawi I can tackle a few of the conflicts. To avoid overlap, I'm going to focus first on: `.travis.yml`, `playbooks/roles/edxapp/tasks/service_variant_config.yml`, `playbooks/roles/nginx/defaults/main.yml`, and `playbooks/roles/nginx/templates/etc/nginx/nginx.conf.j2`. The other ones I'm less familiar with.

**Comment by thraxil** [comment]
@OmarIthawi I handled the ones I'm familiar with. The only ones left should be:

* playbooks/appsemblerPlaybooks/ficus_basic.yml
* playbooks/appsemblerPlaybooks/ficus_enterprise.yml
* playbooks/appsemblerPlaybooks/ficus_pro.yml
* util/install/ansible-bootstrap.sh
* util/parsefiles_config.yml

**Comment by OmarIthawi** [comment]
@thraxil I'm done here. Please review this, unfortunately we have to go almost line by line.

I'll review it too.

**Review by thraxil — APPROVED** [review]
Looks good to me.

**Pull request merged**
