### PR TITLE
Ginkgo Fixups

### PR DESCRIPTION
**Pull request by OmarIthawi**
The merge has been [done](https://trello.com/c/I0uVVCK3). Since the merge is too complicated for review, this PR is a follow up for initial issues that could be broken. 

### Changes
 - Retire pre-ficus playbooks, since there's no need for them in the Ginkgo branch
 - Rename Ficus playbooks to Ginkgo

### Linked Pull Requests: 
 - **Ax:** https://github.com/appsembler/ax/pull/56
 - **edX Platform:** https://github.com/appsembler/edx-platform/pull/211
 - **Configuration:** https://github.com/appsembler/configuration/pull/129
 - **edX Configs:** https://github.com/appsembler/edx-configs/pull/262

### CODE REVIEW

**Comment by OmarIthawi** [comment]
[(8) Ginkgo: Merge the configuration repo](https://trello.com/c/I0uVVCK3/2562-8-ginkgo-merge-the-configuration-repo)

**Comment by OmarIthawi** [comment]
[(8) Buffer for fixes for Ginkgo configuration and edx-platform](https://trello.com/c/0AiqDAB2/2601-8-buffer-for-fixes-for-ginkgo-configuration-and-edx-platform)

**Review by thraxil — APPROVED** [review]
The only good diff is a red diff. :)

**Comment by OmarIthawi** [comment]
Thanks @thraxil! I definitely agree. This is a Work in Progress pull request, thus the `(WIP)` mark, so it could change soon.

**Comment by OmarIthawi** [comment]
[(8) Ginkgo: Deploy a "staging" box](https://trello.com/c/KCiSLOIA/2565-8-ginkgo-deploy-a-staging-box)

**Review by tkeemon — APPROVED** [review]
I like that you deleted a number of the old playbooks. Hopefully that'll prevent people (like myself) from accidentally running Ax/Ansible against a VM with an incorrect Configuration branch loaded. 

:+1:

**Pull request merged**
