### PR TITLE
Merge appsembler/eucalyptus/develop + fixes for Xenial / Ansible 2.2 + merge open-release/ficus.2

### PR DESCRIPTION
**Pull request by mrgnr**
- Merge `appsembler/eucalyptus/develop` (mostly Insights and AMC work)
- Fixes to support Xenial and Ansible 2.2
- Avoid loading plugins defined in the global boto config (see https://github.com/edx/configuration/issues/3766)
- Use TLS to connect to MySQL in the `mysql_init` role if TLS has been configured

### CODE REVIEW

**Comment by mrgnr** [comment]
[(8) Ficus: Create `appsembler/ficus/develop` branch in configuration repo](https://trello.com/c/7ifnxKFQ/915-8-ficus-create-appsembler-ficus-develop-branch-in-configuration-repo)

**Comment by tkeemon** [comment]
I can't link to it in the PR because these lines haven't changed, but Ansible is complaining about a few lines being duplicated in roles/edxapp/defaults/main.yml.

These two lines are being written to *.env.json twice:
- https://github.com/appsembler/configuration/blob/d3786ed7d763b4c30cf40b1a891cf8f157ce7053/playbooks/roles/edxapp/defaults/main.yml#L989-L990
- https://github.com/appsembler/configuration/blob/d3786ed7d763b4c30cf40b1a891cf8f157ce7053/playbooks/roles/edxapp/defaults/main.yml#L999-L1000

And this is being written to cms.env.json:
- https://github.com/appsembler/configuration/blob/d3786ed7d763b4c30cf40b1a891cf8f157ce7053/playbooks/roles/edxapp/defaults/main.yml#L1107

then again to both env.json files here:
- https://github.com/appsembler/configuration/blob/d3786ed7d763b4c30cf40b1a891cf8f157ce7053/playbooks/roles/edxapp/defaults/main.yml#L998

**Comment by mrgnr** [comment]
Thanks @tkeemon, I removed those duplicate settings.

**Comment by mrgnr** [comment]
Thanks for testing this @tkeemon!

**Pull request merged**
