### PR TITLE
Fix CMS celerybeat Supervisor config

### PR DESCRIPTION
**Pull request by bryanlandia**
It was using pidfile and schedule from LMS Celerybeat config
Not worrying about upstream since it has changed to use `single-beat`

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Comment by OmarIthawi** [comment]
Thanks @bryanlandia. We use Celerybeat for Figures on Tahoe SaaS, so I'll have to ask @johnbaldwin for reviewing this change.

The other best reviewers are either Maxi or Anders.


Meanwhile, I would love to know why the change has been done and a little bit of explanation to understand what the change does. I'm asking this because the change looks completely okay, but I don't understand what it does.

**Review by thraxil — APPROVED** [review]

**Comment by bryanlandia** [comment]
Thanks @OmarIthawi .  Turns out configuration repo really only sets up LMS Celerybeat correctly.  For InterSys we have a CMS only Django app and I want CMS Celerybeat and workers to handle its scheduled tasks

**Comment by bryanlandia** [comment]
Thanks for the review @thraxil John, please take a look as well with Figures in mind

**Review by OmarIthawi — APPROVED** [review]
thanks @bryanlandia

**Comment by johnbaldwin** [comment]
I don't see any issues here with regard to Figures.

Figures should be agnostic to specifics for celerybeat and uses the Django settings. Code here: https://github.com/appsembler/figures/blob/master/figures/settings/lms_production.py#L123-L138

**Review by johnbaldwin — APPROVED** [review]

**Pull request merged**
