### PR TITLE
Nginx redirect 502,504 errors to new server-maintenance.html page

### PR DESCRIPTION
**Pull request by bryanlandia**
Make a new `server-maintenance.html` page and redirect 502, 504 errors (gateway timeout, connection refused) errors to it, rather than showing default server error page.

### CODE REVIEW

**Comment by OmarIthawi** [comment]
Looks good to me! Have you actually deployed it?

Just a question, isn't this page available by default? I remember seeing the sinking ship image instead of nginx's default page:

<kbd>Sinking Ship SS Pendleton</kbd>

**Comment by OmarIthawi** [comment]
If I'm missing something, and this is actually required, let's consider contributing this upstream instead of having it sitting in our repo.

**Comment by bryanlandia** [comment]
Thanks guys!

@tkeemon Yeah, it's true, it will display when the backend is not reachable by Nginx.  And agreed 503 is the more accurate code, not 502,504.   edx-platform doesn't have any built-in Maintenance Mode.  The LMS and CMS Nginx templates in `configuration`  support using a maintenance page on S3 for 502 errors. 

```
  error_page 502 @maintenance;

    {% include "s3_maintenance.j2" %}

  {% endif %}
```

I wanted to handle 502 and 504 since we generally take the app servers offline during maintenance, and I wanted to use a server maintenance page that we can configure similar to the error page.  
I'd like to also look at installing the Django Maintenance Mode app so we can then return 503 for all requests while the app servers are running.  https://github.com/fabiocaccamo/django-maintenance-mode  That app allows creating your own template, but we might still want to use the Nginx-level one as  in this PR.

@OmarIthawi We have tried to remove the 'sinking ship' image page for a custom Appsembler branded server error page.  I did deploy this during the NYIF upgrade and it worked well.

**Comment by tkeemon** [comment]
@bryanlandia this has come up for me again. When I try to visit `/admin/organizations/organization/7/`, I get a 504 timeout error from Nginx and a message that says maintenance is in progress. 

I think we may want to rethink this PR before merging it.

**Pull request merged**
