### PR TITLE
Add monitoring and letsencrypt for Ficus

### PR DESCRIPTION
**Pull request by mrgnr**
- Add monitoring playbook which includes:
  - Stackdriver
  - Filebeat and Logstash for ELK logging (requires Java)
  - Snort for network intrusion detection
  - Sysdig for local debugging

- Optionally call the [`letsencrypt`](https://github.com/appsembler/roles/tree/develop/letsencrypt) role to generate TLS certificates. The `letsencrypt` role uses the [webroot](https://letsencrypt.readthedocs.io/en/latest/using.html#webroot) plugin, so nginx must be installed and running beforehand.

When certificates are created behind a load balancer using `letsencrypt`, each server must be able to respond to the challenge from the Let's Encrypt servers. For this reason, the playbook for Enterprise tier calls the [`gcsfuse`](https://github.com/appsembler/roles/tree/develop/gcsfuse) role to mount a Google Storage bucket at the location where `letsencrypt` stores the challenge data. See https://github.com/noderabbit-team/edx-configs/pull/75 for the corresponding configuration.

**Note:** The Ficus playbooks now use roles from the [Appsembler roles](https://github.com/appsembler/roles) repository. To run these playbooks, the repo must be cloned into a directory called `appsembler_roles` next to your `configuration` directory.

### CODE REVIEW

**Comment by mrgnr** [comment]
[(8) Add Let's Encrypt, ELK, and Snort roles to Ficus playbooks](https://trello.com/c/4ORHoOBc/946-8-add-let-s-encrypt-elk-and-snort-roles-to-ficus-playbooks)

**Comment by johnbaldwin** [comment]
@mrgnr Looks pretty obvious, but just wanted to ask: We're ditching stackdriver?

**Comment by mrgnr** [comment]
@johnbaldwin The Stackdriver role lives in our [roles](github.com/appsembler/roles) repo, so I removed the one from `configuration`.

**Comment by johnbaldwin** [comment]
Ahh gotcha, thanks!

**Pull request merged**
