### PR TITLE
Ficus vagrant file

### PR DESCRIPTION
**Pull request by johnbaldwin**
and env file to make it more clear what to source to get devstack ficus running

### CODE REVIEW

**Comment by bryanlandia** [comment]
@johnbaldwin What's the difference between this PR and #78 ?  If one is a duplicate then it should be closed.

**Comment by OmarIthawi** [comment]
> @johnbaldwin What's the difference between this PR and #78 ? If one is a duplicate then it should be closed.

Another ping @johnbaldwin!

BTW I've tried the other one in #78 and it worked just fine:
```
curl -O https://raw.githubusercontent.com/appsembler/configuration/appsembler/ficus/master/vagrant/release/devstack/Vagrantfile
```

So perhaps we should close this.

**Comment by OmarIthawi** [comment]
@johnbaldwin shall we close this one in favor of what's one [master](https://raw.githubusercontent.com/appsembler/configuration/appsembler/ficus/master/vagrant/release/devstack/Vagrantfile)?

**Comment by OmarIthawi** [comment]
@johnbaldwin I'll close this PR, please feel free to open back and consider taking a look at #78.

**Pull request closed without merging**
