### PR TITLE
install rabbitmq earlier in playbook

### PR DESCRIPTION
**Pull request by thraxil**
Since edX actually depends on it for Celery, it should be installed earlier.

My experience is that when it's installed after, `edxapp`, etc. can succeed in installing, but the lms/cms processes will be stuck in a loop failing to start because they can't connect to RabbitMQ. If the whole playbook succeeds, that's usually only for a few minutes and not very noticeable on a new deploy. But if something else fails in between them, we end up with thousands of Sentry events piling up.

Simple fix is to install RabbitMQ earlier in the process before we start on any of the roles that might need it.

### CODE REVIEW

**Review by OmarIthawi — APPROVED** [review]
LGTM!

**Comment by OmarIthawi** [comment]
@thraxil Why don't we use https://www.cloudamqp.com/ ?

**Review by melvinsoft — APPROVED** [review]

**Comment by thraxil** [comment]
@OmarIthawi I'm not opposed to using cloudamqp.com or something like it, but it would be a pretty low priority change, IMO. We're very light users of RabbitMQ and the single instance we run has very low operational overhead (multi-node RabbitMQ clusters are a different story). So we'd be paying at least another $99/month, managing another vendor relationship, having to pull in a 3rd party Terraform provider to provision new instances (https://github.com/cloudamqp/terraform-provider), and introducing another potential GDPR privacy leaking point just to replace a service that takes virtually no server resources or admin time.

If we were going to do anything, I'd be looking at switching Celery to use Redis pub/sub as the broker instead of RabbitMQ since we are already also running Redis as part of the stack. But again, it seems like pretty low reward for the cost.

**Comment by OmarIthawi** [comment]
Thanks @thraxil! Well said.

**Pull request merged**
