### PR TITLE
Merge eucalyptus/develop into eucalyptus master

### PR DESCRIPTION
**Pull request by johnbaldwin**
Ok, it's been too long since this has been merged up to master. Let's comb over it, make sure we're satisfied, and keep a mind on Ficus as we're reviewing this.

Also, if you see someone else who should be a reviewer, please add them in

# Standard message

Configuration Pull Request
---

Make sure that the following steps are done before merging

  - [x] @devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overridden when this goes live?  
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

### CODE REVIEW

**Comment by bryanlandia** [comment]
@johnbaldwin - I think we should go ahead with this merge ASAP.  Looks like there's one conflict now, to do I think with setup for the Scampersand reporting tool.  Is it something you could get to in the next few days?

**Comment by bryanlandia** [comment]
@johnbaldwin - Looks like there are conflicts now since there are new commits since you made the PR.  Do you have bandwidth to check into those?  We do need to get this merged soon so if you need to pass it off or need other help let us know.

**Comment by amirtds** [comment]
@johnbaldwin it looks good to me i think we only need to resolve the scampersand conflict and insights. let me know if i can help here

**Comment by bryanlandia** [comment]
@amirtds I think this one is OK to merge now.  I had to do bring a couple changes that were conflicting into /develop from /master, but I think it should be OK.  Can  you look again?  I want to get rid of the /develop branch as soon as we can.

**Comment by OmarIthawi** [comment]
@johnbaldwin shall we merge this one?

**Comment by tkeemon** [comment]
I'm pretty sure we decided against having a develop/release branching structure for Eucalyptus and later. 

- For Eucalyptus we're going to use `appsembler/eucalyptus/develop` for deployments
- For Ficus and later, we're going to use `appsembler/NAMED_RELEASE/master` for deployments

Closing this PR.

**Pull request closed without merging**
