### PR TITLE
 Added Vagrantfile Appsembler's Gingko (and renamed the Ficus one)

### PR DESCRIPTION
**Pull request by OmarIthawi**
The file has _not_ been tested yet. But I'm afraid of breaking my current Ginkgo box. So you're welcome to try it out.

### CODE REVIEW

**Comment by OmarIthawi** [comment]
[Ginkgo: Make a Vagrantfile](https://trello.com/c/d09xwtPn/2629-ginkgo-make-a-vagrantfile)

**Comment by johnbaldwin** [comment]
@OmarIthawi Trying out the Vagrantfile now. Need to stand up a devstack for Ginkgo for edx-figures anyway, so great timing!

**Comment by natea** [comment]
What's the plan for switching from the Vagrant-based devstack to the Docker-based devstack, given that edX is deprecating the Vagrant way soon?

**Review by johnbaldwin — APPROVED** [review]
I was able to get it to install on a new vm using  the modified vagrantfile @OmarIthawi did

**Comment by OmarIthawi** [comment]
Thanks @johnbaldwin!

**Pull request merged**
