### PR TITLE
EMR fixes for Insights deploy

### PR DESCRIPTION
**Pull request by tkeemon**
This is an ongoing collection of fixes I've needed to make to get our playbooks to correctly deploy Insights for EasyCare.

### CODE REVIEW

**Comment by tkeemon** [comment]
[(16) EasyCare: edX Insights set-up](https://trello.com/c/j5EFjt4O/2408-16-easycare-edx-insights-set-up)

**Comment by tkeemon** [comment]
[(16) EasyCare: edX Insights set-up](https://trello.com/c/j5EFjt4O/2408-16-easycare-edx-insights-set-up)

**Comment by tkeemon** [comment]
@melvinsoft I think we're all set here. Should we pull in someone else to review the changes we've made? Or should we just go ahead and merge them because we're the only two that have any experience with this part of the codebase? 

@OmarIthawi how do you think we should handle this situation?

**Comment by OmarIthawi** [comment]
@tkeemon Two is much better than one, at least we have two engineers who knows the PR. So I'd say go ahead and merge it.

**Comment by tkeemon** [comment]
@OmarIthawi thanks for the feedback. These changes should _mostly_ only affect Insights deployments, so I'm ok merging it.

**Pull request merged**
