### PR TITLE
Comment out dummy django secret key

### PR DESCRIPTION
**Pull request by OmarIthawi**
Just in case someone forgot to set it. This will help to uncover that issue.

This PR is only useful with https://github.com/appsembler/ax/pull/36, since the latter also comments it out from Ax.

### CODE REVIEW

**Comment by OmarIthawi** [comment]
@amirtds since you worked on this role. I think it has a lot of issues! Can we work together and fix them?

**Comment by OmarIthawi** [comment]
[(2) Update our new site deployment checklists to reflect current process](https://trello.com/c/xzkXeaR4/2134-2-update-our-new-site-deployment-checklists-to-reflect-current-process)

**Comment by OmarIthawi** [comment]
@amirtds I've removed the OpenSSL fix from this PR, to avoid duplicating #98. Please check it out when you have time.

**Review by bryanlandia — CHANGES_REQUESTED** [review]
@OmarIthawi - question.  Won't we have a problem with this line which generates `SECRET_KEY` in `*.auth.json` if we have no value here, since there is no fallback value?

https://github.com/appsembler/configuration/blob/appsembler/ficus/master/playbooks/roles/edxapp/defaults/main.yml#L827

**Comment by bryanlandia** [comment]
@OmarIthawi - ahhh,  I see how this works together with ax PR 36.  I'll approve this then, though it might be helpful to change the text from `"DUMMY KEY CHANGE BEFORE GOING TO PRODUCTION"` to something like `"THIS KEY SHOULD BE GENERATED BY AX AND STORED IN SECRETS.YML"` just as a hint.   But it's not super important.

**Review by bryanlandia — APPROVED** [review]

**Comment by melvinsoft** [comment]
@OmarIthawi I just one to raise a couple of thoughts, if we comments one default secret, my first question is "why don't comment/remove them all?" but every change on the default playbooks, is a change to take care when we merge upstream, and since we're already enforcing the secure override of this value with ax.

Also, I think this is going to break devstack spin ups, since we don't use ax or secrets to deploy devstacks.

But I'd like to hear more opinions, if security is above this issues, I'm ok with merge it.

**Review by melvinsoft — COMMENTED** [review]
@OmarIthawi I just one to raise a couple of thoughts, if we comments one default secret, my first question is "why don't comment/remove them all?" but every change on the default playbooks, is a change to take care when we merge upstream, and since we're already enforcing the secure override of this value with ax.

Also, I think this is going to break devstack spin ups, since we don't use ax or secrets to deploy devstacks.

But I'd like to hear more opinions, if security is above this issues, I'm ok with merge it.

**Comment by OmarIthawi** [comment]
@bryanlandia and @melvinsoft I'm closing this PR since it will probably break devstack builds. I've solved the issue in the Ax PR: https://github.com/appsembler/ax/pull/36.

**Pull request closed without merging**
