### PR TITLE
remove AWS role from our hawthorn playbooks

### PR DESCRIPTION
**Pull request by thraxil**
The role is specific to VMs running on AWS so not applicable (and not working) for us.

### CODE REVIEW

**Comment by thraxil** [comment]
[(1) remove AWS role from hawthorn_pro.yml playbook](https://trello.com/c/jMOJOm1I/3867-1-remove-aws-role-from-hawthornproyml-playbook)

**Review by melvinsoft — COMMENTED** [review]
@thraxil Please double check for customers running insights, this role provides a couple of tasks, that creates the tracking log sync script and cron job, that uploads tracking logs to an S3 bucket.

**Comment by thraxil** [comment]
@melvinsoft is it setting stuff on the GCP VMs that are needed for insights? I only removed it from the `edxapp-server` hosts in playbooks that are executing on GCP. 

The problem I ran into was that the last task in `aws`:

```
- name: Update the ssh motd on Ubuntu
  file:
    path: "{{ item.item }}"
    mode: "0644"
  with_items: "{{ motd_files_exist.results }}"
  when:
    - vagrant_home_dir.stat.exists == False and ansible_distribution in common_debian_variants and item.stat.exists
    - cloud_provider == "aws"
```

fails checking the `when` conditional when it runs on GCP: 

```
error while evaluating conditional (vagrant_home_dir.stat.exists == False and ansible_distribution in common_debian_variants and item.stat.exists): 'dict object' has no attribute 'stat'
```

**Comment by melvinsoft** [comment]
@thraxil It shouldn't fail, all the customer have a variable in edx-configs like this: `cloud_provider: "gcp"`. This returns false in the checks. 

If you check customers like UW and OU, they're using the S3 tracking logs uploads.

```
COMMON_OBJECT_STORE_LOG_SYNC: True
COMMON_OBJECT_STORE_LOG_SYNC_BUCKET: "prod-{{ COMMON_DEPLOYMENT }}-db-export"
COMMON_OBJECT_STORE_LOG_SYNC_PREFIX: "logs/tracking/"
COMMON_OBJECT_STORE_LOG_SYNC_SCRIPT: "{{ COMMON_BIN_DIR }}/send-logs-to-object-store"
```

**Comment by thraxil** [comment]
Withdrawing in favor of #241

**Pull request closed without merging**
